In [138]:
# gpu number setting
import os
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ["CUDA_VISIBLE_DEVICES"] = '1' ## gpu 번호 셋팅 윤건 :0, 기준 : 1, 준형 :2,

# Gpu growth setting
import tensorflow as tf
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.compat.v1.Session(config=config)


# tensorflow & keras version check
print('tensorflow version : ' , tf.__version__)
print('keras version : ' , tf.keras.__version__)

# tensorflow gpu available check 
print('GPU available ? : ', tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None))

tensorflow version :  2.3.1
keras version :  2.4.0
GPU available ? :  True

In [139]:
import pandas as pd
import pickle

In [140]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [141]:
with open('../uplus_exp/raw_mod_2.pickle', 'rb') as f:
    data = pickle.load(f)

* buy_history_price \\N 인곳 0원으로 채우기

In [142]:
list(data[data['buy_history_price'] == '\\N'].index)

[1,
 2,
 3,
 6,
 7,
 8,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 55,
 56,
 57,
 58,
 59,
 61,
 64,
 69,
 74,
 75,
 76,
 77,
 79,
 81,
 82,
 83,
 87,
 89,
 90,
 91,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 173,
 174,
 175,
 177,
 178,
 181,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 193,
 194,
 195,
 201,
 206,
 207,
 212,
 213,
 214,
 215,
 216,
 219,
 220,
 222,
 223,
 224,
 225,
 226,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 250,
 251,
 253,
 254,
 255,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 274,
 275,
 276,
 277,
 280,
 281,
 282,
 283,
 284,
 285,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 305,
 306,
 307,
 308,
 309,
 311,
 312,
 314,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 385,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 436,
 438,
 439,
 440,
 442,
 443,
 444,
 445,
 446,
 447,
 449,
 450,
 452,
 462,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 504,
 506,
 508,
 509,
 510,
 511,
 512,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 529,
 530,
 532,
 533,
 534,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 581,
 583,
 584,
 585,
 586,
 587,
 588,
 590,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 677,
 678,
 679,
 680,
 681,
 683,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 704,
 705,
 706,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 737,
 738,
 739,
 741,
 742,
 743,
 744,
 745,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 762,
 763,
 764,
 765,
 766,
 768,
 769,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 797,
 798,
 799,
 800,
 802,
 803,
 808,
 812,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 842,
 849,
 854,
 855,
 856,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 898,
 900,
 901,
 902,
 903,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 931,
 932,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 952,
 953,
 955,
 956,
 957,
 958,
 960,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 989,
 990,
 991,
 992,
 993,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1018,
 1021,
 1025,
 1026,
 1027,
 1029,
 1030,
 1031,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1042,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1052,
 1054,
 1060,
 1061,
 1062,
 1063,
 1064,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1091,
 1092,
 1093,
 1094,
 1096,
 1097,
 1098,
 1099,
 1100,
 1105,
 1106,
 1107,
 1108,
 1110,
 1112,
 1113,
 1114,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1149,
 1150,
 1151,
 1152,
 1153,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1162,
 1163,
 1164,
 1166,
 1167,
 1168,
 1170,
 1171,
 1172,
 1176,
 1177,
 1178,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1194,
 1195,
 1196,
 1197,
 1199,
 1200,
 1203,
 1204,
 1212,
 1213,
 1214,
 1215,
 1218,
 1220,
 1221,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1232,
 1233,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1247,
 1248,
 1249,
 1250,
 1253,
 1254,
 1255,
 1256,
 1257,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1326,
 1328,
 1331,
 1332,
 1334,
 1335,
 1336,
 1337,
 ...]

In [143]:
data.loc[list(data[data['buy_history_price'] == '\\N'].index), ['buy_history_price']] = 0

In [43]:
sparse_features = ['sa_id', 'album_id', 'buy_seg'] + [str(i) for i in range(32)]
dense_features = ['release_date', 'run_time', 'movie_meta_price', 'i30_meta_price', 'buy_tot',
                  'amt_1_4', 'amt_2_4', 'amt_3_4', 'amt_4_4']
ambiguous_features = [ 'agree_yn', 'meta_genre', 'genre_large', 'genre_mid', 'genre_small']
unnecessary_features = ['category_id', # NaN 약 650만 중에 25만 정도.
                        's_time', 'e_time', # future
                        'watch_duration', # future
                        'buy_history_price', # \\N 값이 약 482만 개
                        'vod_s_point', 'vod_e_point', 
                        'album_name',
                        'view_no',
                        'fod', 'buy_1_2', 'buy_3',
                        'amt_r_gabun',
                        'watch_ratio',
                        'weekdays', 'weekends', 'dawn', 'morning', 'afternoon', 'evening',
                        'current_rate']
target = ['ncf_rating']

In [44]:
data['sa_id'].unique()

array([205101491713, 205112221633, 205112403631, ..., 'M17022300005',
       'M17062200019', 'M18061900001'], dtype=object)

In [45]:
print(len(data['album_id'].unique()))
print(len(data['sa_id'].unique()))

10570
968100

* all data -> user_table & content_table

In [46]:
user_tab = data[['sa_id', 'buy_seg', 'buy_tot']]
cont_tab = data[['album_id', 'release_date', 'run_time',
                 'movie_meta_price', 'i30_meta_price', 'buy_history_price',
                'amt_1_4', 'amt_2_4', 'amt_3_4', 'amt_4_4'] + [str(i) for i in range(32)]]

In [47]:
cont_tab

,album_id,release_date,run_time,movie_meta_price,i30_meta_price,buy_history_price,amt_1_4,amt_2_4,amt_3_4,amt_4_4,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
0,M01198J812PPV00,20190424.0,181,2500.0,2500,2500,1,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,M011449172PPV00,20020322.0,115,1400.0,1400,0,1,0,0,0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,M0114CB383PPV00,20031002.0,124,0.0,0,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,M0111CMB08PPV00,20040730.0,100,0.0,1400,0,1,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,M0119A8236PPV00,20190911.0,115,2500.0,2500,2500,0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6759188,M011849006PPV00,20180307.0,101,1400.0,1400,1400,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6759189,M01203Q384PPV00,20200122.0,102,9900.0,9900,0,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False
6759190,M01206H267PPV00,20200604.0,102,5000.0,5000,10000,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6759191,M01206U088PPV00,20200617.0,102,9900.0,9900,18900,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
6759192,M01206B047PPV00,20200527.0,105,3500.0,3500,10000,0,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

In [48]:
user_tab

                sa_id  buy_seg  buy_tot
0        205101491713  VIEW_NO        0
1        205112221633  VIEW_NO        0
2        205112221633  VIEW_NO        0
3        205112221633  VIEW_NO        0
4        205112403631  BUY_1_2        1
...               ...      ...      ...
6759188  M18061900001    BUY_3       14
6759189  M18061900001    BUY_3       14
6759190  M18061900001    BUY_3       14
6759191  M18061900001    BUY_3       14
6759192  M18061900001    BUY_3       14

[6759105 rows x 3 columns]

* duplicate rows 제거

In [54]:
user_uni_tab = user_tab.loc[list(user_tab['sa_id'].drop_duplicates().index)]
cont_uni_tab = cont_tab.loc[list(cont_tab['album_id'].drop_duplicates().index)]

* randomly join?

In [145]:
import random
import numpy as np

In [74]:
def rand_sample(x, n):
    return x.loc[random.sample(list(x.index), n)]

In [ ]:
res = None

for i in range(7000000):
    u = rand_sample(user_uni_tab, 1)
    c = rand_sample(cont_uni_tab, 1)

    values = u.values.tolist()[0] + c.values.tolist()[0]
    cols = list(u.columns) + list(c.columns)

    tmp = pd.DataFrame(data=np.reshape(values, newshape=[1, -1]), columns = cols)

    res = pd.concat([res, tmp])

In [ ]:
res

* 기존 테이블에 있던 조합은 제거